#docker compose file to run both the image that we initially created with the first workflow and the dockerfile for hardhat
services:
  devnet:
    image: ghcr.io/san-est/go-ethereum-devops:9
    command: ["--dev", "--http", "--http.addr", "0.0.0.0", "--http.port", "8545", "--http.api", "eth,net,web3"]
    ports:
      - "8545:8545"

  hardhat:
    build: .
    depends_on:
      - devnet
    ports:
      - "8545:8545"