name: Docker Image Build and Push to ghcr

on:
  pull_request:
    branches: [ "master" ]
    types: [ labeled ]

  # Adding this so that I can test my jobs and run workflows manually from the Actions tab in the repository
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: san-est/go-ethereum-devops

jobs:
  build-and-push:
    if: ${{ github.event.label.name == 'CI:Build' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Login to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
